/**
 * Centralized Human Review Constants for Stage 5
 */
const REVIEW_TYPES = Object.freeze({
  CLASSIFICATION: 'CLASSIFICATION',
  FIELD: 'FIELD',
  VALIDATION: 'VALIDATION'
});

const REVIEW_STATUS = Object.freeze({
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  REJECTED: 'REJECTED'
});

const REVIEW_REASONS = Object.freeze({
  LOW_CLASSIFICATION_CONFIDENCE: 'LOW_CLASSIFICATION_CONFIDENCE',
  UNKNOWN_DOCUMENT_TYPE: 'UNKNOWN_DOCUMENT_TYPE',
  AMBIGUOUS_DOCUMENT_TYPE: 'AMBIGUOUS_DOCUMENT_TYPE',
  UNCERTAIN_PAGE_BOUNDARY: 'UNCERTAIN_PAGE_BOUNDARY',
  CLASSIFIER_DISAGREEMENT: 'CLASSIFIER_DISAGREEMENT',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  LOW_FIELD_CONFIDENCE: 'LOW_FIELD_CONFIDENCE',
  INVALID_DATE: 'INVALID_DATE',
  INVALID_FORMAT: 'INVALID_FORMAT',
  ARITHMETIC_MISMATCH: 'ARITHMETIC_MISMATCH',
  DUPLICATE_DETECTED: 'DUPLICATE_DETECTED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INSUFFICIENT_PAGE_CONTENT: 'INSUFFICIENT_PAGE_CONTENT',
  OTHER: 'OTHER'
});

module.exports = {
  REVIEW_TYPES,
  REVIEW_STATUS,
  REVIEW_REASONS
};
