/**
 * Centralized Processing Statuses for Document Intelligence Platform
 */
const PROCESSING_STATUS = Object.freeze({
  UPLOADED: 'UPLOADED',
  QUEUED: 'QUEUED',
  PREPROCESSING: 'PREPROCESSING',
  EXTRACTING: 'EXTRACTING',
  CLASSIFYING: 'CLASSIFYING',
  STRUCTURING: 'STRUCTURING',
  VALIDATING: 'VALIDATING',
  NEEDS_REVIEW: 'NEEDS_REVIEW',
  APPROVED: 'APPROVED',
  FAILED: 'FAILED',
  RETRYING: 'RETRYING',
  REJECTED: 'REJECTED'
});

const VALIDATION_STATUS = Object.freeze({
  PASSED: 'PASSED',
  FAILED: 'FAILED',
  NEEDS_REVIEW: 'NEEDS_REVIEW'
});

module.exports = {
  PROCESSING_STATUS,
  VALIDATION_STATUS
};
